"""Shared static constants (extensions, rule-keyword tables) + the strategy fingerprint manifest."""

from __future__ import annotations

import hashlib
import json
from services.config import (
    CACHE_SCHEMA_VERSION,
    MAX_AUDIT_SOURCE_FILES,
    MAX_CODE_CHUNKS,
    MAX_FILE_SIZE,
    MAX_TREE_FILES,
    OVERSIZED_HEAD_CHARS,
    OVERSIZED_MAX_WINDOWS,
    OVERSIZED_TAIL_CHARS,
    OVERSIZED_WINDOW_RADIUS,
    TOTAL_CHARS_LIMIT
)

import logging

logger = logging.getLogger(__name__)

CODE_EXTENSIONS = {
    ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs",
    ".py", ".pyw",
    ".java", ".kt", ".scala",
    ".go", ".rs", ".c", ".cpp", ".h", ".hpp",
    ".rb", ".php", ".cs", ".swift",
    ".vue", ".svelte",
    ".sh", ".bash", ".zsh",
    ".sql", ".graphql",
    ".html", ".htm", ".css", ".scss", ".less", ".sass",
    ".json", ".yaml", ".yml", ".toml", ".xml", ".ini", ".cfg",
    ".md", ".txt", ".env",
}

SKIP_DIRS = {
    "node_modules", ".git", "__pycache__", ".svn", ".hg",
    "dist", "build", "out", "target", ".next", ".nuxt",
    "vendor", ".venv", "venv", "env", ".tox",
    ".idea", ".vscode", ".vs",
}

RISK_KEYWORDS = {
    "rce": [
        "exec(", "eval(", "system(", "shell_exec", "passthru(", "popen(", "subprocess",
        "runtime.exec", "processbuilder", "child_process", "os.system", "pickle.loads",
        "yaml.load(", "marshal.loads", "deserialize", "unserialize",
        "assert(", "compile(", "proc_open", "pcntl_exec", "vm.run",
        "class.forname", "scriptengine", "objectinputstream", "readobject(",
        "os/exec", "exec.command", "spawn(", "ioctl(", "syscall(",
        "codebase", "jinja2", "freemarker", "velocity", "ognl", "spel",
    ],
    "injection": [
        "select ", "insert ", "update ", "delete ", "execute(", "executemany(", "raw(",
        "cursor", "query(", "$where", "mongodb", "redis", "sql", "orm", "statement",
        "preparedstatement", "jdbctemplate", "hibernate", "mybatis",
        "sequelize", "knex", "typeorm", "prisma", "mongoose",
        "db.query", "db.exec", "gorm", "sqlx",
        "ldap_search", "ldap_bind", "graphql", "mutation {",
        "executescript(", "rawsql", "raw_query", "text(",
    ],
    "xss": [
        "innerhtml", "outerhtml", "document.write", "dangerouslysetinnerhtml", "v-html",
        "render(", "template", "onclick", "onerror", "<script", "htmlspecialchars",
        "v-text", "insertadjacenthtml", "domparser", "contenteditable",
        "srcdoc", "javascript:", "data:", "postmessage(",
        "bypasssecuritytrust", "domsanitizer", "[innerhtml]",
        "strip_tags", "sanitize", "escape", "encodeuri",
    ],
    "auth": [
        "auth", "login", "logout", "session", "cookie", "jwt", "token", "oauth",
        "password", "captcha", "permission", "authorize", "role", "csrf",
        "signin", "signup", "authenticate", "bearer", "verify_token",
        "saml", "samlresponse", "kerberos", "ntlm",
        "recaptcha", "hcaptcha", "totp", "mfa", "2fa",
        "bcrypt", "argon2", "pbkdf2", "scrypt",
        "rate_limit", "throttle", "lockout", "login_attempts",
        "refresh_token", "access_token", "antiforgerytoken",
    ],
    "file": [
        "upload", "download", "file_get_contents", "fopen(", "readfile(", "open(",
        "realpath", "path", "os.path", "shutil", "zip", "tar", "../", "..\\",
        "move_uploaded_file", "attachment",
        "file_put_contents", "unlink(", "mkdir(", "rmdir(", "copy(", "rename(",
        "scandir(", "opendir(", "readdir(", "glob(", "basename(", "dirname(",
        "tempfile", "tmpfile", "symlink", "readlink",
        "fs.readfile", "fs.writefile", "fs.unlink",
        "files.delete", "files.copy", "multipartfile",
        "os.open", "os.create", "filepath.join",
        "extractto", "ziparchive", "phar(",
        "..%2f", "..%5c", "%2e%2e",
    ],
    "config": [
        ".env", "secret", "apikey", "api_key", "password", "token", "private_key",
        "access_key", "credentials", "config", "settings", "docker", "compose",
        "secret_key", "app_secret", "api_secret",
        "db_password", "database_url", "debug=true", "debug=1",
        "cors_origin", "allowed_hosts", "allowed_origins",
        "aws_secret", "azure_key", "gcp_key",
        "ssl", "tls", "certificate", "0.0.0.0",
        "nginx", "apache", "kubernetes", "k8s",
        "github_token", "slack_token", "stripe_key",
        "package.json", "requirements.txt", "pom.xml", "go.mod",
        ".git", ".svn", "backup.sql", "dump.sql",
    ],
    "business": [
        "order", "payment", "amount", "price", "inventory", "coupon", "balance",
        "workflow", "status", "business", "tenant", "owner",
        "refund", "withdraw", "deposit", "transfer", "recharge",
        "invoice", "billing", "receipt", "tax",
        "discount", "promo", "voucher", "reward",
        "stock", "quantity", "sku",
        "approve", "reject", "cancel", "confirm",
        "merchant", "seller", "buyer", "customer",
        "settlement", "commission", "profit", "margin",
        "points", "level", "vip", "membership",
        "quota", "limit", "threshold", "cap",
    ],
}

RULE_LABEL_STAGE_MAP = {
    "rce": [2],
    "injection": [3],
    "xss": [4],
    "auth": [5, 6],
    "config": [7],
    "file": [8],
    "business": [9],
    "ssrf": [2, 3],
    "xxe": [2, 3],
    "crypto": [5, 7],
}

RULE_HIT_KEYWORDS = {
    "rce": [
        # ---- Python ----
        "exec(", "eval(", "system(", "os.system", "os.popen", "popen(", "subprocess",
        "subprocess.call", "subprocess.run", "subprocess.Popen", "subprocess.check_output",
        "subprocess.check_call", "os.exec", "os.spawn", "commands.getoutput",
        "pickle.loads", "pickle.load(", "cPickle.loads", "shelve.open",
        "yaml.load(", "yaml.unsafe_load(", "yaml.full_load(", "ruamel.yaml",
        "marshal.loads", "marshal.load(", "shutil.unpack_archive",
        "codebase.exec", "codebase.eval", "compile(",
        # ---- PHP ----
        "shell_exec", "passthru(", "system(", "exec(", "popen(",
        "proc_open", "pcntl_exec", "pcntl_fork",
        "unserialize(", "assert(", "preg_replace(", "create_function(",
        "call_user_func(", "call_user_func_array(",
        # ---- Java ----
        "runtime.exec", "runtime.getruntime", "processbuilder", "processbuilder(",
        "class.forname", "getruntime().exec", "scriptengine", "nashorn",
        "objectinputstream", "readobject(", "xmldecoder", "xstream",
        "ysoserial", "invocationhandler", "rmi://",
        # ---- Node.js / JavaScript ----
        "child_process", "child_process.exec", "child_process.spawn",
        "child_process.fork", "require('child_process')",
        "vm.runincontext", "vm.runinnewcontext", "vm.runinthiscontext",
        "new function(", "settimeout(", "setinterval(",
        "function(", "eval(",
        # ---- Go ----
        "os/exec", "exec.command", "exec.commandcontext", "cmd.run",
        "cmd.start", "cmd.output", "cmd.combinedoutput",
        # ---- Ruby ----
        "system(", "exec(", "ioctl(", "syscall(", "spawn(",
        "open(", "open3.", "io.popen", "kernel.system",
        "eval(", "binding.eval", "instance_eval", "class_eval",
        # ---- .NET / C# ----
        "process.start", "processstartinfo", "diagnostics.process",
        # ---- Deserialization / General ----
        "deserialize(", "from_json", "object_from", "json_serializable",
        "jsonpickle", "jsonpickle.decode", "jsonpickle.encode",
        "objectmapper.readvalue", "jackson.readvalue",
        "fastjson", "fastjson.parse", "gson.fromjson",
        "kotlinx.serialization", "swift.jsondecoder",
        # ---- Template injection ----
        "jinja2", "jinja2.template", "render_template_string",
        "mako.template", "tornado.template", "freemarker",
        "velocity", "thymeleaf", "twig", "smarty", "erb(",
        "stringtemplate", "handlebars.compile", "mustache.render",
        "nunjucks", "ejs.render", "pug.render",
        # ---- Expression Language ----
        "el(", "${", "#{", "ognl", "spel", "mvel",
    ],
    "injection": [
        # ---- SQL - General ----
        "select ", "select*", "insert into", "insert ", "update ", "update ",
        "delete from", "delete ", "drop table", "drop database", "truncate ",
        "alter table", "create table", "union select", "union all",
        # ---- Python DB ----
        "execute(", "executemany(", "executescript(", "query(", "prepare(",
        "raw(", "cursor.execute", "cursor.executemany",
        "rawsql", "raw_query", "execute_sql", "text(",
        "sqlalchemy", ".execute(", ".from_sql",
        ".extra(", ".rawquery", ".raw(", ".createorreplace",
        "sqlite3.execute", "sqlite3.connect",
        # ---- PHP DB ----
        "mysqli_query", "mysqli_fetch", "mysqli_prepare", "mysqli_real_query",
        "mysql_query", "mysql_fetch", "mysql_db_query",
        "pg_query", "pg_send_query", "pg_prepare", "pg_execute",
        "sqlsrv_query", "oci_execute", "oci_parse",
        "pdo->query", "pdo->exec", "pdo->prepare",
        "sqlite_query", "sqlite_single_query", "sqlite_exec",
        "oci_parse", "ora_exec", "ingres_query",
        # ---- Java DB ----
        "preparedstatement", "statement.execute", "statement.executequery",
        "statement.executeupdate", "jdbctemplate.query", "jdbctemplate.update",
        "jdbctemplate.execute", "namedparameterjdbctemplate",
        "hibernate.createquery", "hibernate.createsqlquery",
        "entitymanager.createnativequery", "session.createsqlquery",
        "mybatis select", "mybatis insert", "mybatis update",
        # ---- Node.js / JS DB ----
        "sequelize.query", "sequelize.raw", "knex.raw", "knex.whereRaw",
        "typeorm.query", "typeorm.querybuilder", "prisma.$queryraw",
        "mongoose.where", "mongodb.find", "mongodb.aggregate",
        # ---- Go DB ----
        "db.query", "db.exec", "db.queryrow", "db.queryrowcontext",
        "gorm.raw", "gorm.exec", "xorm.exec", "sqlx.query",
        # ---- NoSQL ----
        "$where", "$gt", "$lt", "$ne", "$or", "$and", "$regex", "$expr",
        "mongodb", "mongo.find", "mongo.aggregate", "mongo.where",
        "redis", "redis.get", "redis.set", "redis.eval",
        # ---- ORM / Query Builder ----
        "orm", "statement", "createorreplace", "buildquery",
        ".filter(", ".annotate(", ".aggregate(", ".extra(",
        # ---- GraphQL / LDAP ----
        "graphql", "mutation {", "query {", "fragment",
        "ldap_search", "ldap_bind", "ldap_add",
    ],
    "xss": [
        # ---- DOM Manipulation ----
        "innerhtml", "outerhtml", "document.write", "document.writeln",
        "writeln", "insertadjacenthtml", "insertadjacenttext",
        "domparser", "parsefromstring", "createtextnode",
        "createelement", "createelementns", "appendchild",
        "replacechild", "insertbefore", "setattribute",
        "innerhtml =", "outerhtml =",
        # ---- React / Vue / Angular ----
        "dangerouslysetinnerhtml", "dangerouslysetinnerhtml:",
        "v-html", "v-text", "v-bind:html",
        "{{{", "::", "[innerhtml]",
        "bypasssecuritytrusthtml", "bypasssecuritytrustresourceurl",
        "bypasssecuritytrustscript", "bypasssecuritytrusturl",
        "sanitizer.bypasssecuritytrust", "domsanitizer",
        # ---- Event Handlers ----
        "<script", "onerror=", "onclick=", "onload=", "onmouseover=",
        "onfocus=", "onblur=", "onsubmit=", "onchange=",
        "oninput=", "onkeydown=", "onkeyup=", "onkeypress=",
        "onmousedown=", "onmouseup=", "ondblclick=",
        "ondrag=", "ondragstart=", "ondragend=",
        "oncontextmenu=", "onanimationend=",
        # ---- PHP Output ----
        "echo\"", "echo '", "echo $_get", "echo $_post", "echo $_request",
        "echo $_server", "echo htmlspecialchars", "echo htmlentities",
        "print(", "printf(", "sprintf(", "vprintf(",
        # ---- Encoding / Sanitization (signals mitigation or need for it) ----
        "htmlspecialchars", "htmlentities", "strip_tags",
        "ent_quotes", "ent_html5",
        "sanitize", "escape", "encodeuri", "encodeuricomponent",
        "xss", "contenteditable", "contenteditable=",
        # ---- Misc ----
        "srcdoc", "srcdoc=", "data:", "javascript:",
        "object.data", "embed.src", "iframe.src",
        "location.href", "location.replace", "location.assign",
        "document.referrer", "window.name",
        "postmessage(", "receivemessage",
        "eval(", "settimeout(", "setinterval(",
        "new function(",
    ],
    "auth": [
        # ---- Authentication ----
        "login", "logout", "signin", "signup", "sign_in", "sign_up",
        "signout", "sign_out", "register", "authenticate",
        "password", "passwd", "pwd", "pass_hash",
        "password_hash", "password_verify", "password_check",
        "password_reset", "forgot_password", "change_password",
        "changepassword", "updatepassword",
        # ---- Session Management ----
        "session_start", "session_regenerate_id", "session_destroy",
        "session_id", "session_id(", "session.cookie",
        "setcookie", "setcookie(", "setrawcookie(",
        "session", "cookie(", "cookie", "cookies",
        "remember", "remember_me", "persistent",
        "session fixation", "session hijacking",
        # ---- JWT / Token ----
        "jwt", "jsonwebtoken", "jwt.encode", "jwt.decode",
        "jwt.verify", "jwttoken", "jwt_token",
        "bearer", "bearer ", "authorization:", "authorization: bearer",
        "token", "verify_token", "validate_token", "refresh_token",
        "access_token", "id_token", "auth_token",
        "tokeninvalid", "tokenexpired", "tokenverify",
        "jwks", "jwks_uri", "openid-configuration",
        # ---- OAuth / SSO ----
        "oauth", "oauth2", "oauth_callback", "oauth_token",
        "client_id", "client_secret", "redirect_uri",
        "authorization_code", "grant_type",
        "saml", "samlresponse", "saml_assertion",
        "cas(", "kerberos", "ntlm",
        # ---- CSRF ----
        "csrf", "_csrf", "xsrf", "csrftoken", "csrf_token",
        "antiforgerytoken", "antiforgery", "validatantiforgerytoken",
        "x-csrf-token", "x-xsrf-token",
        # ---- Multi-Factor ----
        "captcha", "recaptcha", "hcaptcha", "turnstile",
        "totp", "hotp", "mfa", "2fa", "otp",
        "sms_code", "verification_code", "authenticator",
        # ---- Brute Force Protection ----
        "rate_limit", "rate_limiter", "throttle",
        "lockout", "login_attempts", "failed_attempts",
        "account_lock", "max_attempts",
        # ---- Password Storage ----
        "md5(", "sha1(", "sha256", "bcrypt", "scrypt", "argon2",
        "pbkdf2", "crypt(",
        "password_hash", "password_needs_rehash",
    ],
    "config": [
        # ---- Environment / Secrets ----
        ".env", ".env.local", ".env.production", ".env.development",
        "secret", "secret_key", "secret_key_base", "app_secret",
        "api_key", "apikey", "api_secret",
        "private_key", "privatekey", "private_key_path",
        "access_key", "accesskey", "access_secret",
        "credentials", "credential", "aws_credential",
        "db_password", "database_url", "database_host",
        "db_host", "db_user", "db_name", "db_pass",
        "token=", "token =", "bearer ",
        # ---- Hardcoded Values ----
        "password=", "password =", "passwd=",
        "hardcoded", "hardcode", "plaintext",
        "debug=true", "debug = true", "debug=1", "debug=true",
        "debug_mode", "debug = 1", "app_debug",
        "trace=true", "trace_enabled",
        "verbose=true", "logging=debug",
        # ---- CORS / Network ----
        "allowed_hosts", "allowed_origins", "cors_origin",
        "cors_allow", "cors_enabled", "access-control-allow",
        "access-control-allow-origin", "access-control-allow-credentials",
        "access-control-allow-methods", "access-control-allow-headers",
        # ---- Server Config ----
        "config", "settings", "configuration",
        "docker", "compose", "docker-compose", "dockerfile",
        "kubernetes", "k8s", "helm", "chart.yaml",
        "nginx", "apache", "httpd.conf", ".htaccess",
        "ssl", "tls", "https", "certificate", "cert_file",
        "server_name", "server_port", "bind_address",
        "0.0.0.0", "listen 80", "listen 443",
        # ---- Cloud / SaaS Keys ----
        "aws_secret", "aws_access_key", "s3_secret",
        "azure_key", "azure_connection_string",
        "gcp_key", "gcp_service_account", "google_api_key",
        "sendgrid_key", "stripe_key", "mailgun_key",
        "twilio_sid", "twilio_token",
        "github_token", "gitlab_token", "slack_token", "slack_webhook",
        # ---- Dependency / Supply Chain ----
        "requirements.txt", "package.json", "package-lock.json",
        "yarn.lock", "gemfile", "gemfile.lock",
        "pom.xml", "build.gradle", "go.sum", "go.mod",
        "cargo.lock", "composer.json", "composer.lock",
        "pip.conf", "npmrc", ".npmrc", "pypirc",
        # ---- Backup / Exposed Files ----
        ".git", ".svn", ".hg", "backup.sql", "dump.sql",
        ".ds_store", "thumbs.db", "web.config", "app.config",
    ],
    "file": [
        # ---- PHP File Operations ----
        "move_uploaded_file", "readfile(", "file_get_contents", "file_put_contents",
        "fopen(", "fread(", "fwrite(", "fclose(",
        "unlink(", "mkdir(", "rmdir(", "copy(", "rename(",
        "file(", "file_exists(", "is_file(", "is_dir(",
        "parse_ini_file(", "parse_url(", "pathinfo(",
        # ---- PHP Upload ----
        "move_uploaded_file", "is_uploaded_file",
        "$_files", "upload_max_filesize", "tmp_name",
        # ---- PHP Directory ----
        "basename(", "dirname(", "scandir(", "opendir(", "readdir(",
        "glob(", "chdir(", "chroot(", "realpath(",
        "ziparchive", "extractto", "zip->open", "zip->extractto",
        "phar(", "phar://",
        # ---- Python File Operations ----
        "open(", "os.path", "os.path.join", "os.path.abspath",
        "os.path.realpath", "os.path.basename", "os.path.dirname",
        "os.listdir", "os.walk", "os.remove", "os.rmdir", "os.mkdir",
        "os.makedirs", "os.rename", "os.chmod", "os.chown",
        "shutil.copy", "shutil.move", "shutil.rmtree",
        "shutil.unpack_archive", "shutil.make_archive",
        "pathlib", "pathlib.path",
        "tempfile", "tempfile.mktemp", "tempfile.namedtemporaryfile",
        # ---- Java File Operations ----
        "new file(", "fileinputstream", "fileoutputstream",
        "filereader", "filewriter", "randomaccessfile",
        "files.delete", "files.copy", "files.move",
        "files.walk", "files.list", "files.readallbytes",
        "files.write", "files.newbufferedreader",
        "multipartfile", "part.write", "part.getinputstream",
        "transfersto", "inputstream",
        # ---- Node.js File Operations ----
        "fs.readfile", "fs.writefile", "fs.unlink",
        "fs.mkdir", "fs.rmdir", "fs.rename", "fs.copyfile",
        "fs.createreadstream", "fs.createwritestream",
        "fs.readdir", "fs.stat", "fs.exists",
        "require('fs')", "import fs from",
        "busboy", "multer", "formidable", "multiparty",
        # ---- Go File Operations ----
        "os.open", "os.create", "os.readfile", "os.writefile",
        "os.remove", "os.rename", "os.mkdirall",
        "filepath.join", "filepath.clean", "filepath.walk",
        "io.copy", "io.readall", "io.util.readall",
        "archive/zip", "archive/tar", "compress/gzip",
        # ---- General ----
        "download", "upload", "attachment", "export", "import",
        "archive", "backup", "restore",
        "sendfile", "send_file", "download(",
        "content-disposition", "content-type",
        "../", "..\\", "..%2f", "..%5c", "%2e%2e",
        "path_traversal", "directory traversal",
        "symlink", "readlink", "lstat",
        "tmp", "temp", "tmp_name", "tmpfile",
    ],
    "business": [
        # ---- E-Commerce / Trading ----
        "order", "orders", "order_id", "order_status",
        "payment", "pay", "checkout", "purchase", "transaction",
        "amount", "price", "total", "subtotal", "fee",
        "currency", "exchange_rate", "rate",
        "discount", "coupon", "promo", "promotion", "voucher",
        "balance", "account_balance", "credit", "debit",
        "refund", "refund_amount", "chargeback", "return",
        "withdraw", "withdrawal", "deposit", "transfer",
        "recharge", "topup", "cash",
        # ---- Inventory ----
        "inventory", "stock", "stock_quantity", "quantity",
        "sku", "product_id", "item_id",
        "restock", "replenish", "out_of_stock",
        # ---- Workflow / State ----
        "workflow", "status", "state_machine",
        "approve", "reject", "cancel", "confirm",
        "pending", "completed", "failed",
        "review", "audit", "verify", "validate",
        # ---- Multi-Tenant / Ownership ----
        "business", "tenant", "tenant_id", "owner", "owner_id",
        "merchant", "seller", "buyer", "customer",
        "org", "organization_id", "company_id",
        # ---- Financial ----
        "invoice", "billing", "receipt", "tax",
        "profit", "margin", "commission",
        "settlement", "clearing", "ledger",
        "bank_account", "card_number", "cvv",
        "secrets", "dividend", "bonus",
        # ---- User Assets ----
        "points", "reward", "gift", "prize",
        "level", "rank", "vip", "membership",
        "privilege", "entitlement",
        # ---- Rate / Quota ----
        "quota", "limit", "cap", "threshold",
        "daily_limit", "max_amount", "min_amount",
        "rate_limit", "frequency",
    ],
    "ssrf": [
        # ---- Python HTTP Clients ----
        "requests.get(", "requests.post(", "requests.put(", "requests.delete(",
        "requests.patch(", "requests.head(", "requests.options(",
        "requests.request(", "requests.session",
        "urllib.request", "urlopen(", "urlretrieve(",
        "urllib2.urlopen", "urllib.request.urlopen",
        "http.client", "http.client.httpconnection", "http.client.httpsconnection",
        "httplib2", "httpx.get", "httpx.post",
        "aiohttp", "aiohttp.session", "asyncio",
        # ---- PHP HTTP Clients ----
        "curl_exec", "curl_init", "curl_setopt",
        "file_get_contents(", "stream_context_create",
        "fsockopen(", "pfsockopen(",
        "guzzle", "guzzlehttp", "guzzle->get", "guzzle->post",
        # ---- Java HTTP Clients ----
        "httpurlconnection", "url.openconnection",
        "httpclient", "okhttp", "okhttpcall",
        "resttemplate", "webclient", "feign.client",
        "url(", "new url(", "url.openstream",
        "httpget", "httppost",
        # ---- Node.js HTTP Clients ----
        "http.get", "http.request", "https.get", "https.request",
        "fetch(", "axios", "axios.get", "axios.post",
        "got(", "node-fetch", "superagent", "needle",
        "request(", "unirest",
        # ---- Go HTTP Clients ----
        "http.get(", "http.post(", "http.newrequest",
        "http.client", "http.defaultclient",
        "resty", "req", "go-resty",
        # ---- Ruby HTTP Clients ----
        "net/http", "open-uri", "httparty",
        "httparty.get", "httparty.post",
        "curb", "typhoeus",
        # ---- .NET HTTP Clients ----
        "webclient", "webrequest", "httpwebrequest",
        "httpclient", "restsharp",
        # ---- Cloud / Internal ----
        "metadata", "metadata.google.internal",
        "169.254.169.254", "instance-metadata",
        "ec2_metadata", "imds",
        "localhost", "127.0.0.1", "0.0.0.0",
        "internal", "private", "intranet",
        # ---- URL Parsing ----
        "redirect", "url_redirect", "location:",
        "header('location", "response.redirect",
        "redirect_url", "return_url", "next=",
        "url=", "uri=", "dest=", "target=",
    ],
    "xxe": [
        # ---- Java XML Parsers ----
        "xmlinputfactory", "saxparser", "saxparserfactory",
        "documentbuilder", "documentbuilderfactory",
        "xmlreader", "xmlreaderfactory", "saxbuilder",
        "saxreader", "domparser", "xmlreader",
        "transformerfactory", "saxtransformerfactory",
        "schemafactory", "validator",
        "xmlconfiguration", "blobserializer",
        # ---- Python XML Parsers ----
        "xml.etree", "xml.etree.elementtree", "elementtree",
        "xml.dom", "xml.dom.minidom", "xml.sax",
        "lxml.etree", "lxml.objectify", "defusedxml",
        "fromstring(", "parse(", "xml.parse(",
        "expat", "pyexpat", "xml.parsers.expat",
        # ---- PHP XML Parsers ----
        "simplexml_load_string", "simplexml_load_file",
        "domdocument", "domxpath", "xml_parse",
        "xml_parser_create", "xml_set_element_handler",
        "xmldocument", "simplexmlelement",
        # ---- .NET XML Parsers ----
        "xmlreader", "xmlreader.create", "xmldocument",
        "xmltextreader", "xmlvalidatingreader",
        "xpathdocument", "xpathnavigator",
        "xmlserializer", "datacontractserializer",
        # ---- Go XML Parsers ----
        "encoding/xml", "xml.unmarshal", "xml.decoder",
        "xml.newdecoder",
        # ---- Node.js XML Parsers ----
        "libxmljs", "xml2js", "fast-xml-parser",
        "sax", "xml-stream",
        # ---- General XXE Patterns ----
        "entity", "<!entity", "<!doctype",
        "system ", "public ", "external",
        "parameter entity", "general entity",
        "dtd", "external dtd", "external entity",
        "xxe", "xinclude",
        "soap", "wsdl", "svg", "xlsx", "docx",
    ],
    "crypto": [
        # ---- Weak Hash Algorithms ----
        "md5(", "md5.new", "md5.hexdigest", "hashlib.md5",
        "sha1(", "sha1.new", "sha1.hexdigest", "hashlib.sha1",
        # ---- Weak Ciphers ----
        "des", "3des", "tripledes", "des-ede3",
        "rc4", "rc2", "blowfish",
        "ecb", "aes_ecb", "aes-128-ecb", "ecb_mode",
        "cipher(", "cipheriv", "createcipher",
        "aes_ecb", "des_ecb", "des_cbc",
        # ---- Weak Key Sizes ----
        "aes-128", "rsa-1024", "rsa-2048",
        "key_size=128", "key_length=128",
        # ---- Insecure Random ----
        "random.random(", "random.randint(", "random.randrange(",
        "math.random(", "math.random",
        "java.util.random", "system.random",
        "np.random", "numpy.random",
        "secrets", "secrets.token", "uuid.uuid",
        # ---- Hardcoded Keys ----
        "aes_key", "encryption_key", "secret_key",
        "signing_key", "hmac_key", "salt",
        "iv=", "initialization_vector", "nonce=",
        "padding", "pkcs5", "pkcs7", "oaep",
        # ---- Certificate / TLS Issues ----
        "verify=false", "ssl_verify=false", "insecure",
        "tls_skip_verify", "ssl._create_unverified_context",
        "check_hostname=false", "cert_reqs=cert_none",
        "rejectunauthorized=false", "strictssl=false",
        # ---- Password Hashing ----
        "base64(", "b64encode", "b64decode",
        "encode(", "decode(",
        "rot13", "caesar", "atob(", "btoa(",
    ],
}

RULE_HIT_MIN_HITS = {
    "rce": 1,
    "injection": 1,
    "xss": 1,
    "auth": 1,
    "config": 1,
    "file": 1,
    "business": 2,
    "ssrf": 1,
    "xxe": 1,
    "crypto": 1,
}

RULE_HIT_TIERS = {
    "rce": {
        "strong": [
            "exec(", "eval(", "system(", "os.system", "os.popen", "popen(",
            "subprocess.Popen", "subprocess.call", "subprocess.run",
            "subprocess.check_output", "subprocess.check_call",
            "runtime.exec", "runtime.getruntime", "processbuilder",
            "child_process.exec", "child_process.spawn", "child_process.fork",
            "pickle.loads", "pickle.load(", "cPickle.loads",
            "yaml.load(", "yaml.unsafe_load(", "marshal.loads",
            "shell_exec", "passthru(", "proc_open", "pcntl_exec",
            "unserialize(", "deserialize(", "objectinputstream", "readobject(",
            "vm.runincontext", "vm.runinnewcontext", "class.forname",
            "objectmapper.readvalue", "xstream",
        ],
        "medium": [
            "subprocess", "os.exec", "os.spawn", "commands.getoutput",
            "shelve.open", "yaml.full_load(", "ruamel.yaml",
            "marshal.load(", "shutil.unpack_archive",
            "codebase.exec", "codebase.eval", "compile(",
            "pcntl_fork", "process.start", "processstartinfo",
            "jsonpickle", "jsonpickle.decode", "fastjson",
            "gson.fromjson", "jackson.readvalue",
            "new function(", "require('child_process')",
            "os/exec", "exec.command", "exec.commandcontext",
            "assert(", "ioctl(", "syscall(",
            "jinja2", "freemarker", "velocity", "thymeleaf",
            "render_template_string", "mako.template",
            "twig", "smarty", "erb(", "ejs.render",
            "ognl", "spel", "mvel",
            "invocationhandler", "scriptengine", "nashorn",
            "stringtemplate", "handlebars.compile",
            "binding.eval", "instance_eval", "class_eval",
            "kernel.system", "open3.", "io.popen",
        ],
    },
    "injection": {
        "strong": [
            "select ", "insert into", "update ", "delete from",
            "execute(", "executemany(", "executescript(",
            "cursor.execute", "cursor.executemany",
            "query(", "raw(", "rawsql", "raw_query",
            ".extra(", ".rawquery",
            "mysqli_query", "mysql_query", "pg_query", "sqlsrv_query", "oci_execute",
            "pdo->query", "pdo->exec", "pdo->prepare",
            "preparedstatement", "statement.execute", "statement.executequery",
            "jdbctemplate.query", "jdbctemplate.update", "jdbctemplate.execute",
            "hibernate.createquery", "hibernate.createsqlquery",
            "entitymanager.createnativequery",
            "$where", "$gt", "$lt", "$ne", "$regex", "$expr",
            "sequelize.query", "sequelize.raw", "knex.raw", "knex.whereRaw",
            "typeorm.query", "prisma.$queryraw",
            "db.query", "db.exec", "gorm.raw", "sqlx.query",
        ],
        "medium": [
            "prepare(", "createorreplace",
            "insert ", "delete ", "drop table", "truncate ",
            "union select", "union all",
            "cursor", "text(", "orm", "statement",
            "sqlite_query", "sqlite3.execute",
            "mybatis select", "mybatis insert", "mybatis update",
            "mongo.find", "mongo.aggregate", "mongoose.where",
            "redis.eval", "redis.get",
            "graphql", "mutation {", "query {",
            "ldap_search", "ldap_bind",
            "sqlalchemy", ".execute(", ".from_sql",
        ],
    },
    "xss": {
        "strong": [
            "innerhtml", "outerhtml", "document.write", "document.writeln",
            "dangerouslysetinnerhtml", "v-html",
            "insertadjacenthtml", "domparser",
            "srcdoc", "javascript:", "data:",
            "bypasssecuritytrusthtml", "bypasssecuritytrusturl",
            "bypasssecuritytrustscript", "bypasssecuritytrustresourceurl",
            "onerror=", "onclick=", "onload=",
            "<script", "echo\"<script", "echo '<script",
        ],
        "medium": [
            "v-text", "v-bind:html", "[innerhtml]", "{{{",
            "writeln", "insertadjacenttext",
            "parsefromstring", "createtextnode",
            "object.data", "embed.src", "iframe.src",
            "location.href", "location.replace", "location.assign",
            "postmessage(", "receivemessage",
            "contenteditable", "contenteditable=",
            "domsanitizer", "sanitizer.bypasssecuritytrust",
            "onmouseover=", "onfocus=", "onsubmit=",
            "echo $_get", "echo $_post", "echo $_request",
            "htmlspecialchars", "strip_tags", "sanitize", "escape",
            "encodeuri", "encodeuricomponent",
            "new function(", "settimeout(", "setinterval(",
        ],
    },
    "auth": {
        "strong": [
            "login", "logout", "session_start", "session_regenerate_id",
            "session_destroy", "setcookie", "setrawcookie(",
            "jwt", "jsonwebtoken", "jwt.encode", "jwt.decode", "jwt.verify",
            "bearer", "authorization: bearer",
            "oauth", "oauth2", "saml", "samlresponse",
            "password_hash", "password_verify", "password_check",
            "verify_token", "validate_token", "authenticate",
            "csrf", "_csrf", "xsrf", "antiforgerytoken", "csrftoken",
            "captcha", "recaptcha", "hcaptcha", "totp", "mfa", "2fa",
            "bcrypt", "argon2", "pbkdf2", "scrypt",
        ],
        "medium": [
            "signin", "signup", "sign_in", "sign_up",
            "signout", "sign_out", "register",
            "password", "passwd", "pwd",
            "password_reset", "forgot_password", "change_password",
            "session", "cookie(", "cookie", "cookies",
            "token", "refresh_token", "access_token", "auth_token",
            "jwks", "openid-configuration",
            "client_id", "client_secret", "redirect_uri",
            "authorization_code", "grant_type",
            "kerberos", "ntlm", "cas(",
            "remember", "remember_me",
            "rate_limit", "rate_limiter", "throttle", "lockout",
            "login_attempts", "failed_attempts",
            "otp", "sms_code", "verification_code",
            "md5(", "sha1(", "sha256", "crypt(",
            "x-csrf-token", "x-xsrf-token",
        ],
    },
    "config": {
        "strong": [
            ".env", ".env.local", ".env.production",
            "secret_key", "app_secret", "api_secret",
            "api_key", "apikey", "private_key", "privatekey",
            "access_key", "accesskey", "access_secret",
            "credentials", "credential", "aws_credential",
            "db_password", "database_url",
            "aws_secret", "aws_access_key",
            "azure_key", "azure_connection_string",
            "gcp_key", "gcp_service_account",
            "sendgrid_key", "stripe_key", "mailgun_key",
            "github_token", "gitlab_token", "slack_token", "slack_webhook",
            "twilio_sid", "twilio_token",
            "debug=true", "debug = true", "debug=1",
            "password=", "password =", "passwd=",
        ],
        "medium": [
            "secret", "token=", "token =", "bearer ",
            "allowed_hosts", "allowed_origins", "cors_origin",
            "cors_allow", "access-control-allow-origin",
            "ssl", "tls", "certificate", "cert_file",
            "config", "settings", "configuration",
            "docker", "compose", "docker-compose", "dockerfile",
            "kubernetes", "k8s", "helm",
            "nginx", "apache", "httpd.conf", ".htaccess",
            "server_name", "0.0.0.0",
            "database_host", "db_host", "db_user", "db_name", "db_pass",
            "google_api_key",
            "requirements.txt", "package.json", "pom.xml", "go.mod",
            "pip.conf", ".npmrc", "pypirc",
            ".git", ".svn", "backup.sql", "dump.sql",
            "verify=false", "ssl_verify=false", "insecure",
        ],
    },
    "file": {
        "strong": [
            "move_uploaded_file", "is_uploaded_file",
            "file_get_contents", "file_put_contents",
            "fopen(", "fread(", "fwrite(",
            "readfile(", "unlink(", "mkdir(", "rmdir(",
            "copy(", "rename(",
            "ziparchive", "extractto", "phar(",
            "realpath", "basename(", "scandir(",
            "opendir(", "readdir(", "glob(",
            "shutil.rmtree", "shutil.copy", "shutil.move",
            "shutil.unpack_archive",
            "fs.unlink", "fs.readfile", "fs.writefile",
            "multipartfile",
            "move_uploaded_file", "sendfile", "send_file",
            "filepath.clean",
        ],
        "medium": [
            "upload", "download", "attachment",
            "archive", "backup", "import", "export",
            "pathinfo(", "dirname(",
            "open(", "os.path.join", "os.path.abspath",
            "os.listdir", "os.walk", "os.remove",
            "tempfile", "mktemp", "symlink", "readlink",
            "files.delete", "files.copy", "files.move",
            "filepath.join", "os.path",
            "../", "..\\", "..%2f", "..%5c",
            "content-disposition", "content-type",
            "tmp", "temp", "tmp_name",
            "fs.createwritestream", "fs.createreadstream",
            "busboy", "multer", "formidable",
            "new file(", "fileinputstream", "fileoutputstream",
        ],
    },
    "business": {
        "strong": [
            "order", "orders", "order_id", "order_status",
            "payment", "checkout", "purchase", "transaction",
            "amount", "price", "total", "subtotal",
            "coupon", "discount", "promo", "promotion", "voucher",
            "balance", "account_balance",
            "refund", "refund_amount", "chargeback",
            "withdraw", "withdrawal", "deposit", "transfer",
            "inventory", "stock", "stock_quantity",
        ],
        "medium": [
            "currency", "exchange_rate", "fee", "rate",
            "credit", "debit", "recharge", "topup",
            "quantity", "sku", "product_id",
            "restock", "out_of_stock",
            "workflow", "status", "state_machine",
            "approve", "reject", "cancel", "confirm",
            "invoice", "billing", "receipt", "tax",
            "settlement", "commission", "profit", "margin",
            "merchant", "seller", "buyer", "customer",
            "points", "reward", "level", "vip", "membership",
            "quota", "threshold", "limit", "cap",
            "daily_limit", "max_amount", "min_amount",
        ],
    },
    "ssrf": {
        "strong": [
            "requests.get(", "requests.post(", "requests.put(", "requests.delete(",
            "requests.request(", "requests.session",
            "urllib.request", "urlopen(", "urlretrieve(",
            "curl_exec", "curl_init", "curl_setopt",
            "http.get(", "http.post(", "http.newrequest",
            "httpurlconnection", "url.openconnection",
            "guzzlehttp", "guzzle->get", "guzzle->post",
            "fetch(", "axios", "axios.get", "axios.post",
            "okhttp", "resttemplate", "webclient",
            "new url(", "url.openstream",
            "169.254.169.254", "metadata.google.internal",
        ],
        "medium": [
            "urllib2.urlopen", "http.client", "httpx.get", "httpx.post",
            "aiohttp", "asyncio",
            "file_get_contents(", "fsockopen(", "pfsockopen(",
            "http.get", "http.request", "https.get", "https.request",
            "got(", "node-fetch", "superagent", "needle",
            "net/http", "open-uri", "httparty",
            "webclient", "webrequest", "httpwebrequest", "restsharp",
            "redirect", "url_redirect", "location:",
            "return_url", "next=", "url=", "dest=",
            "localhost", "127.0.0.1", "0.0.0.0",
            "internal", "private", "intranet",
        ],
    },
    "xxe": {
        "strong": [
            "xmlinputfactory", "saxparser", "saxparserfactory",
            "documentbuilder", "documentbuilderfactory",
            "xmlreader", "xmlreaderfactory",
            "transformerfactory", "saxtransformerfactory",
            "xml.etree", "xml.etree.elementtree",
            "lxml.etree", "lxml.objectify",
            "simplexml_load_string", "simplexml_load_file",
            "domdocument", "domxpath",
            "xmlreader.create", "xmldocument", "xmltextreader",
            "encoding/xml", "xml.unmarshal", "xml.newdecoder",
            "<!entity", "<!doctype",
        ],
        "medium": [
            "saxbuilder", "saxreader", "domparser",
            "xml.dom", "xml.dom.minidom", "xml.sax",
            "defusedxml", "expat", "pyexpat",
            "xml_parse", "xml_parser_create",
            "xmlserializer", "datacontractserializer",
            "libxmljs", "xml2js", "fast-xml-parser",
            "entity", "dtd", "external entity",
            "xxe", "xinclude",
            "soap", "wsdl", "svg",
        ],
    },
    "crypto": {
        "strong": [
            "md5(", "md5.new", "hashlib.md5",
            "sha1(", "sha1.new", "hashlib.sha1",
            "des", "rc4", "ecb", "aes_ecb",
            "verify=false", "ssl_verify=false",
            "ssl._create_unverified_context",
            "check_hostname=false", "cert_reqs=cert_none",
            "rejectunauthorized=false", "strictssl=false",
            "tls_skip_verify",
        ],
        "medium": [
            "3des", "tripledes", "blowfish", "rc2",
            "aes-128", "rsa-1024",
            "cipher(", "cipheriv", "createcipher",
            "random.random(", "randint(", "math.random(",
            "java.util.random",
            "aes_key", "encryption_key", "hmac_key",
            "base64(", "b64encode", "b64decode",
            "iv=", "nonce=", "padding",
            "rot13", "atob(", "btoa(",
        ],
    },
}

RULE_HIT_MIN_WEIGHTED = {
    "rce": 3,
    "injection": 3,
    "xss": 3,
    "auth": 4,
    "config": 3,
    "file": 3,
    "business": 4,
    "ssrf": 3,
    "xxe": 3,
    "crypto": 3,
}

def _build_analysis_strategy_fingerprint() -> str:
    payload = {
        "cache_schema_version": CACHE_SCHEMA_VERSION,
        "max_file_size": MAX_FILE_SIZE,
        "max_tree_files": MAX_TREE_FILES,
        "max_audit_source_files": MAX_AUDIT_SOURCE_FILES,
        "max_code_chunks": MAX_CODE_CHUNKS,
        "total_chars_limit": TOTAL_CHARS_LIMIT,
        "oversized_head_chars": OVERSIZED_HEAD_CHARS,
        "oversized_tail_chars": OVERSIZED_TAIL_CHARS,
        "oversized_max_windows": OVERSIZED_MAX_WINDOWS,
        "oversized_window_radius": OVERSIZED_WINDOW_RADIUS,
        "skip_dirs": sorted(SKIP_DIRS),
        "code_extensions": sorted(CODE_EXTENSIONS),
        "risk_keywords": {key: list(value) for key, value in sorted(RISK_KEYWORDS.items())},
        "rule_label_stage_map": {key: list(value) for key, value in sorted(RULE_LABEL_STAGE_MAP.items())},
        "rule_hit_keywords": {key: list(value) for key, value in sorted(RULE_HIT_KEYWORDS.items())},
        "rule_hit_min_hits": dict(sorted(RULE_HIT_MIN_HITS.items())),
        "rule_hit_tiers": {k: {"strong": sorted(v.get("strong", [])), "medium": sorted(v.get("medium", []))} for k, v in sorted(RULE_HIT_TIERS.items())},
        "rule_hit_min_weighted": dict(sorted(RULE_HIT_MIN_WEIGHTED.items())),
    }
    serialized = json.dumps(payload, ensure_ascii=False, sort_keys=True)
    return hashlib.sha256(serialized.encode("utf-8", errors="ignore")).hexdigest()

__all__ = [
    'CODE_EXTENSIONS',
    'SKIP_DIRS',
    'RISK_KEYWORDS',
    'RULE_LABEL_STAGE_MAP',
    'RULE_HIT_KEYWORDS',
    'RULE_HIT_MIN_HITS',
    'RULE_HIT_TIERS',
    'RULE_HIT_MIN_WEIGHTED',
    '_build_analysis_strategy_fingerprint',
]
